/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export type ScriptCategory =
    | { __kind__: "DiscordBots" }
    | { __kind__: "WebScraping" }
    | { __kind__: "Automation" };

export interface Script {
    id: bigint;
    title: string;
    description: string;
    category: ScriptCategory;
    price: bigint;
    version: string;
    downloadUrl: string;
    languageTag: string;
    createdAt: bigint;
}

export interface Purchase {
    id: bigint;
    buyerPrincipal: Principal;
    scriptId: bigint;
    purchasedAt: bigint;
}

export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    registerCaller(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<{ username: string; email: string; } | null>;
    getCallerUserRole(): Promise<UserRole>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: { username: string; email: string; }): Promise<void>;
    addScript(title: string, description: string, category: ScriptCategory, price: bigint, version: string, downloadUrl: string, languageTag: string): Promise<bigint>;
    updateScript(id: bigint, title: string, description: string, category: ScriptCategory, price: bigint, version: string, downloadUrl: string, languageTag: string): Promise<boolean>;
    deleteScript(id: bigint): Promise<boolean>;
    listScripts(): Promise<Script[]>;
    getScript(id: bigint): Promise<Script | null>;
    grantPurchase(buyer: Principal, scriptId: bigint): Promise<boolean>;
    recordPurchase(scriptId: bigint): Promise<boolean>;
    getMyPurchasedScripts(): Promise<Script[]>;
    getDownloadUrl(scriptId: bigint): Promise<string | null>;
    hasUserPurchased(scriptId: bigint): Promise<boolean>;
    listAllPurchases(): Promise<Purchase[]>;
    listAllUsers(): Promise<{ principal: Principal; username: string; email: string; }[]>;
}
import type { UserRole as _UserRole, ScriptCategory as _ScriptCategory, Script as _Script, Purchase as _Purchase, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async registerCaller(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCaller();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<{ username: string; email: string; } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: { username: string; email: string; }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async addScript(arg0: string, arg1: string, arg2: ScriptCategory, arg3: bigint, arg4: string, arg5: string, arg6: string): Promise<bigint> {
        const candid_cat = to_candid_ScriptCategory(arg2);
        if (this.processError) {
            try {
                return await this.actor.addScript(arg0, arg1, candid_cat, arg3, arg4, arg5, arg6);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.addScript(arg0, arg1, candid_cat, arg3, arg4, arg5, arg6);
        }
    }
    async updateScript(arg0: bigint, arg1: string, arg2: string, arg3: ScriptCategory, arg4: bigint, arg5: string, arg6: string, arg7: string): Promise<boolean> {
        const candid_cat = to_candid_ScriptCategory(arg3);
        if (this.processError) {
            try {
                return await this.actor.updateScript(arg0, arg1, arg2, candid_cat, arg4, arg5, arg6, arg7);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.updateScript(arg0, arg1, arg2, candid_cat, arg4, arg5, arg6, arg7);
        }
    }
    async deleteScript(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                return await this.actor.deleteScript(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.deleteScript(arg0);
        }
    }
    async listScripts(): Promise<Script[]> {
        if (this.processError) {
            try {
                const result = await this.actor.listScripts();
                return result.map(from_candid_Script);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listScripts();
            return result.map(from_candid_Script);
        }
    }
    async getScript(arg0: bigint): Promise<Script | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getScript(arg0);
                return result.length === 0 ? null : from_candid_Script(result[0]);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScript(arg0);
            return result.length === 0 ? null : from_candid_Script(result[0]);
        }
    }
    async grantPurchase(arg0: Principal, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                return await this.actor.grantPurchase(arg0, arg1);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.grantPurchase(arg0, arg1);
        }
    }
    async recordPurchase(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                return await this.actor.recordPurchase(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.recordPurchase(arg0);
        }
    }
    async getMyPurchasedScripts(): Promise<Script[]> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPurchasedScripts();
                return result.map(from_candid_Script);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPurchasedScripts();
            return result.map(from_candid_Script);
        }
    }
    async getDownloadUrl(arg0: bigint): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDownloadUrl(arg0);
                return result.length === 0 ? null : result[0];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDownloadUrl(arg0);
            return result.length === 0 ? null : result[0];
        }
    }
    async hasUserPurchased(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                return await this.actor.hasUserPurchased(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.hasUserPurchased(arg0);
        }
    }
    async listAllPurchases(): Promise<Purchase[]> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllPurchases();
                return result.map(from_candid_Purchase);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllPurchases();
            return result.map(from_candid_Purchase);
        }
    }
    async listAllUsers(): Promise<{ principal: Principal; username: string; email: string; }[]> {
        if (this.processError) {
            try {
                return await this.actor.listAllUsers();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.listAllUsers();
        }
    }
}
function from_candid_ScriptCategory(value: _ScriptCategory): ScriptCategory {
    if ('DiscordBots' in value) return { __kind__: 'DiscordBots' };
    if ('WebScraping' in value) return { __kind__: 'WebScraping' };
    return { __kind__: 'Automation' };
}
function to_candid_ScriptCategory(value: ScriptCategory): _ScriptCategory {
    if (value.__kind__ === 'DiscordBots') return { DiscordBots: null };
    if (value.__kind__ === 'WebScraping') return { WebScraping: null };
    return { Automation: null };
}
function from_candid_Script(value: _Script): Script {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        category: from_candid_ScriptCategory(value.category),
        price: value.price,
        version: value.version,
        downloadUrl: value.downloadUrl,
        languageTag: value.languageTag,
        createdAt: value.createdAt,
    };
}
function from_candid_Purchase(value: _Purchase): Purchase {
    return {
        id: value.id,
        buyerPrincipal: value.buyerPrincipal,
        scriptId: value.scriptId,
        purchasedAt: value.purchasedAt,
    };
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        username: string;
        email: string;
    }]): {
    username: string;
    email: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
